### ISSUE TITLE
Discord client is closed source

### ISSUE THREAD

**Issue by 10by10pixel** [discordapp/discord-open-source#101]
If the Discord client is "free" (of charge) software, why is it not free (libre) software? Are there plans to open source or a timeline available?

**Comment by Woeler** [comment]
Because their business model is based on nitro support and centralized servers? The chance of it going open source is probably near to null. There is a major difference between "free" as in "free speech" and "free" as in "free beer".

**Comment by 10by10pixel** [comment]
Making the client open source wouldn't impact their business model at all? There's a difference between a client and a server. The client would be like the HTML/CSS/JS in your browser. The source is already visible might as well unobfuscate it and allow people with free time to contribute.

**Comment by 10by10pixel** [comment]
Also, @Woeler 
"free as in beer" = free of charge
"free as in speech" = "libre"

You'll find I addressed these terms in my original post just maybe not in ways you're familiar with.

**Comment by Woeler** [comment]
Except that this isn't like the html/css/js of a website. It's more like the PHP of a website, which will allow you to reverse engineer the other end of the software, having little preventing your from hosting your own, and circumventing Discord as a firm entirely.

**Comment by jfurrow** [comment]
This repository is used to feature communities using Discord as a primary means of communication, so let's keep it on-topic, please.

**Comment by lukeeey** [comment]
Just passing by and pointing out that the client is essentially just a chrome webview.

**Comment by StefanCristian** [comment]
Well, might as well make it FOSS, maybe it will get uber-boosted & optimized by community

**Comment by teppyboy** [comment]
bruh chromium based client @lukeeey and custom titlebar

**Comment by lukeeey** [comment]
I did say "essentially", meaning its basically the same thing as chromium, just with extra google features.

**Comment by 10by10pixel** [comment]
I meant the HTML/CSS/JS that Chrome webview is running. Same as making the front-end for the website opensource

**Comment by Poliwrath** [comment]
Bump

**Comment by sparr** [comment]
@Woeler You already have the whole source code to the discord client. It's unencrypted in the archive file `discord/resources/app.asar` on any computer with Discord installed.

**Comment by nobody5050** [comment]
Bump
