### ISSUE TITLE
Can't get server verified

### ISSUE THREAD

**Issue by tannisroot** [discordapp/discord-open-source#146]
Hi, I've contacted opensource@discordapp.com about a week ago about getting the server of the project I manage verified (https://github.com/discordapp/discord-open-source/pull/139), but unfortunately I still got response.
Is there a reason for that? Also, is there maybe another way to contact Discord about verifying the server?

**Comment by N0tMyFaultOG** [comment]
I also contacted them under the same email address a month ago, but received no response either.
It would be a bummer if we both used the wrong mail address.

**Comment by jfurrow** [comment]
Sorry for the delays here and thanks for your patience!

That is the correct email address and it is reviewed by real human beings. I'll work with these humans to figure out a way to respond to these emails in a more timely fashion.

**Comment by tannisroot** [comment]
Still not reply from you guys. Can this be reopened until it's fully resolved, please? Thanks.

**Comment by N0tMyFaultOG** [comment]
Give them some time, they might need to work out a concept first to respond and act faster on open requests. Where reviewing pull requests are dealt with in an appropriate manner, reviewing and working thru the mails are (hopefully) done like that as well.

**Comment by tannisroot** [comment]
@N0tMyFaultOG is there any ETA on when they are going to figure that out? We have a release shipping soon and I would really like to include a custom link in it as the release after that will take quite a while to come out.

**Comment by N0tMyFaultOG** [comment]
@tannisroot I've no clue, in a few days my application is pending for 2 month. I don't know when they will come back to us or what they are doing for months and dont have the time to read over a few lines. I'm used to receive way faster responses from the discord team, but unfortunately we can't do more then waiting.

**Comment by tannisroot** [comment]
Can this be reopened please? I haven't received a reply in a month.
