### ISSUE TITLE
Invalid invite code

### ISSUE THREAD

**Issue by dunielpls** [discordapp/discord-open-source#159]
As the title says. Shall I remove it before adding my server?

Additional information:

```
Could not validate some community codes!

Tachiyomi (2dDQBv2): { code: 10006, message: 'Unknown Invite' }

Failed to validate invite codes
```

**Edit**: It looks like there are four other pull requests waiting, so I am sending my PR as-is.

**Comment by jfurrow** [comment]
@dunielpls I'll handle this separately, thanks for pointing it out!

**Comment by jfurrow** [comment]
I removed the community in https://github.com/discordapp/discord-open-source/commit/022e2589f697b694fd1505a9605dcef2b9254b7f

I also asked for a new invite code in the original PR https://github.com/discordapp/discord-open-source/pull/62
