### ISSUE TITLE
Clarification sought on when a project might actually get shown...

### ISSUE THREAD

**Issue by SlySven** [discordapp/discord-open-source#173]
Having recently gotten our project into this *open-source* listing I was wondering when/how often it will actually appear on https://discordapp.com/open-source? I guess you have some sort of random selection process that pulls some of the - currently 94 (?) projects - but how often does that change and what is the formula for how many are chosen each time - so far we do *not* seem to have been lucky!

Having done the work I just wanted to be able to point other people at it to show it off... :grinning:

**Comment by jfurrow** [comment]
Communities are listed in order of acceptance, so yours is at the bottom of the list after clicking "View more":
![Screen Shot 2019-05-10 at 4 25 36 PM](https://user-images.githubusercontent.com/1134755/57561397-4f79e300-7340-11e9-831d-fb1cf1c587ba.png)
