### ISSUE TITLE
The Songoda Community

### ISSUE THREAD

**Issue by Mr-Deej** [discordapp/discord-open-source#174]
This Songoda and the Owner Brianna have broken multiple parts of Discord's TOS and Guidelines. 
If the information regarding self-harm by itself is not enough for the removal of this user from discord's open source page or her discord server, then there is a google drive with multiple folders and in each folder a README that explains the contents of the folder as well as provides any additional information. Attached at the bottom of this page is a link to the evidence drive.
In regards to Self-Harm which is the main cause for this report, this user (Brianna) had messaged InstantzzHD, someone who did not like the products made by Songoda, her business. She messaged this user and told him that if he did not stop hurting her business, that she would start hurting herself. She continues saying this to him and he gets very worried as one would. She then shows him the knife she would use to cut herself, asks him where he should, and then goes and cuts herself there. This experience was something that horrified InstantzzHD for a while. Once she realized what she did was wrong, she did the best she could to cover this up which includes essentially bribing the user saying that if he talks about it again any money she sent to him would be taken back. 
This means that the user was very reluctant to do anything with this information. Included are the message links to some of the more horrifying messages that she had sent to him.
She uses the discord server she owns named Songoda (Also known as Songoda Universe, Songoda Enterprise, and Songoda Entertainment) which is a verified server and because of the reputation she gets from that server, she is able to act this way with little to no repercussions. 
If the user is removed from discord as well as the Songoda discord deleted, that would mean that the user, Brianna, will no longer have an outlet for these activities which are very clearly unsafe to the users in the community. I have also linked a pr that removes her branding for this repository.

~Kind regards MrDeej

[Evidence drive](https://www.dropbox.com/s/apzh6bda9ygg377/Evidence.zip?dl=0)
https://www.dropbox.com/s/apzh6bda9ygg377/Evidence.zip?dl=0

[Pull Request](https://github.com/discordapp/discord-open-source/pull/175)
https://github.com/discordapp/discord-open-source/pull/175

**Comment by AeSix** [comment]
HI. 
This is an issue reporting service for reporting issues with the code of the open source components of Discordapp's software.  This is not a moderation reporting service.  I highly suggest that, for the sake of you actually getting anything accomplished, that you review your issue, determine if you're being appropriate in reporting this, and then reporting it in the appropriate place.  Which is not a github code issues service.  

Additionally, I highly suggest getting a life and stop trying to police the entire internet.  Your ulcers will thank you.

**Comment by PhanaticD** [comment]
saw this on discord, this is obviously just harassment its totally unrelated, i agree with aesix

**Comment by Esophose** [comment]
You mean the very same InstantzZHD who is currently on the Songoda staff team? Why would he be on the Songoda team if he was, as you put, "horrified"?
As mentioned above, this clearly isn't the appropriate place to be posting things like that. You should really report that to the correct party, or more preferably, just mind your own business.

**Comment by 0xC1A551C** [comment]
What the fuck did you just fucking say about Songoda, you little bitch? I'll have you know Songoda graduated top of the class in the Minecraft Community, and we've been involved in numerous secret raids on Mojang, and I have over 3000 confirmed mob kills. We am trained in gorilla warfare and I'm the top bow sniper in the entire Songoda armed forces. You are nothing to me but just another fishing rod target. We will wipe you the fuck out with precision the likes of which has never been seen before on this Minecraft world, mark my fucking text. You think you can get away with saying that shit to us over the Internet? Think again, fucker. As we speak we are contacting my secret network of songoda spies across the internet and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. we can be anywhere, anytime, and we can kill you in over seven hundred ways, and that's just with my bare fist. Not only are we extensively trained in unarmed combat, but we have access to the entire arsenal of the Minecraft Gamer Community and I will use java to its full extent to wipe your miserable ass off the face of the Minecraft Community, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking keyboard. But you couldn't, you didn't, and now you're paying the price, you goddamn piece of bedrock. Songoda will shit creepers all over you and you will drown in it. You're fucking dead, kiddo.

**Comment by AeSix** [comment]
annnnd that was completely appropriate... how?

**Comment by AeSix** [comment]
@jfurrow please close this.

**Comment by LaxWasHere** [comment]
I just want to be included before it gets closed. That being said "Regardless of my stance on the person being reported, this not the appropriate place to do so."
![yes](https://media.giphy.com/media/tFK8urY6XHj2w/giphy.gif)

**Comment by jfurrow** [comment]
Please submit requests at https://support.discordapp.com/hc/en-us/requests/new
