### ISSUE TITLE
Sound or mic not working after connecting

### ISSUE THREAD

**Issue by nextlooper42** [discordapp/discord-open-source#65]
When is app running and someone plug headphones (or change number of channels of audio device) or/and plug in microphone/webcam. That device is not working until Discord reboot.

When is audio device plugged in or changed number of channels = audio stop working in app
When mic/webcam is plugged = that device is not working until app restart

These are app breaking bugs, please fix them ASAP

Platform: Windows 10 (10.0.17134.48)

**Comment by jfurrow** [comment]
@nextlooper42 This repository is meant for open source communities that use Discord. For help with the product, please visit https://support.discordapp.com/hc/en-us. Thanks!
