### ISSUE TITLE
Question about Open Source development Groups

### ISSUE THREAD

**Issue by Asherslab** [discordapp/discord-open-source#80]
Hey there, I've got an interesting question. I'm a lead developer for a Open Source development group, and we develop quite a few things and each of them have their own discords (Not mentioning our private development discord itself),  Our largest project just reached over 1,000 Discord members, and we were wondering how to go about our Pull Request.

Should we apply under our name "LDT" itself, or apply for this specific project?

**Comment by jfurrow** [comment]
Is there a public Discord server that's used for the group, or just the individual project servers?

**Comment by Asherslab** [comment]
there isn't a public one used for the group, only individual ones for each of out projects, and a private one for our inter-developer chat

**Comment by jfurrow** [comment]
In that case you should submit a PR to feature the specific project and community with over 1,000 members.

**Comment by Asherslab** [comment]
thank you
